org: lucasnad27
app: universe-for-the-day
service: universe-for-the-day

frameworkVersion: '2'

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221

functions:
  getAllStocks:
    handler: handler.run
    environment:
      S3_BUCKET: ${param:S3_BUCKET}
    events:
      # Invoke Lambda function every day
      - schedule: cron(15 18 * * ? *)

