name: Deploy dev release

on:
  push:
    branches:
      - main

jobs:
  deploy:
    defaults:
      run:
        working-directory: src
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
    - run: npm ci
    - run: npm i -g serverless@2.x
    - run: serverless deploy --stage dev
      env:
        SERVERLESS_ACCESS_KEY: ${{ secrets.SERVERLESS_ACCESS_KEY }}
